package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"prc-11/graph/model"
	"prc-11/services/graphql/store"
)

// // CreateTask is the resolver for the createTask field.
// func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
// 	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
// }

// // UpdateTask is the resolver for the updateTask field.
// func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
// 	panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
// }

// // DeleteTask is the resolver for the deleteTask field.
// func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
// 	panic(fmt.Errorf("not implemented: DeleteTask - deleteTask"))
// }

// // Tasks is the resolver for the tasks field.
// func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
// 	panic(fmt.Errorf("not implemented: Tasks - tasks"))
// }

// // Task is the resolver for the task field.
// func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
// 	panic(fmt.Errorf("not implemented: Task - task"))
// }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	for _, t := range store.Tasks {
		if t.ID == id {
			return &model.Task{
				ID:          t.ID,
				Title:       t.Title,
				Description: t.Description,
				Done:        t.Done,
			}, nil
		}
	}
	return nil, nil
}

func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	result := make([]*model.Task, 0, len(store.Tasks))
	for _, t := range store.Tasks {
		result = append(result, &model.Task{
			ID:          t.ID,
			Title:       t.Title,
			Description: t.Description,
			Done:        t.Done,
		})
	}
	return result, nil
}

func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	id := fmt.Sprintf("t_%03d", len(store.Tasks)+1)

	task := &store.Task{
		ID:          id,
		Title:       input.Title,
		Description: input.Description,
		Done:        false,
	}

	store.Tasks = append(store.Tasks, task)

	return &model.Task{
		ID:          task.ID,
		Title:       task.Title,
		Description: task.Description,
		Done:        task.Done,
	}, nil
}

func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	for _, t := range store.Tasks {
		if t.ID == id {
			if input.Title != nil {
				t.Title = *input.Title
			}
			if input.Description != nil {
				t.Description = input.Description
			}
			if input.Done != nil {
				t.Done = *input.Done
			}

			return &model.Task{
				ID:          t.ID,
				Title:       t.Title,
				Description: t.Description,
				Done:        t.Done,
			}, nil
		}
	}
	return nil, fmt.Errorf("task not found")
}

func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	for i, t := range store.Tasks {
		if t.ID == id {
			store.Tasks = append(store.Tasks[:i], store.Tasks[i+1:]...)
			return true, nil
		}
	}
	return false, nil
}
